package hudson.plugins.denglish;

import java.util.Random;

public class FactGenerator {

    /**
     * The configured denglish facts, from http://ithinkispider.com/
     */
    private static final String[] FACTS = {
                    "I understand just train-station - Ich versteh nur Bahnhof",
                    "sorry, my englisch is under all pig - Entschuldige, mein Englisch ist unter aller Sau",
                    "I think I spider - Ich glaub ich spinne",
                    "the devil will i do - Den Teufel werd ich tun",
                    "my lovely mister singing club - Mein lieber Herr Gesangsverein",
                    "come on...jump over your shadow - Komm schon...spring über Deinen Schatten",
                    "you walk me animally on the cookie - Du gehst mir tierisch auf den Keks",
                    "there my hairs stand up to the mountain - Da stehen mir die Haare zu Berge",
                    "tell me nothing from the horse - Erzähl mir keinen vom Pferd",
                    "don´t ask after sunshine - Frag nicht nach Sonnenschein",
                    "it´s not good cherry-eating with you - Es ist nicht gut Kirschen essen mit Dir",
                    "now it goes around the sausage - Jetzt geht´s um die Wurst",
                    "there are you on the woodway - Da bist Du auf dem Holzweg",
                    "holla the woodfairy - Holla die Waldfee",
                    "I hold it in head not out - Ich halt´s im Kopf nicht aus",
                    "now butter by the fishes - Jetzt mal Butter bei die Fische",
                    "I see black for you - Ich seh Schwarz für Dich",
                    "your are such a fear-rabbit - Du bist so ein Angsthase",
                    "known home luck alone - Trautes heim, Glück allein",
                    "are you save? - Bist Du sicher?",
                    "give not so on - Gib nicht so an",
                    "heaven, ass and thread! - Himmel, Arsch und Zwirn!",
                    "Human Meier - Mensch Meier",
                    "you have not more all cups in the board - Du hast nicht mehr alle Tassen im Schrank",
                    "she had a circleruntogetherbreak - Sie hatte einen Kreislaufzusammenbruch",
                    "I know me here out - Ich kenn mich hier aus",
                    "I fall from all clouds - Ich fall aus allen Wolken",
                    "no one can reach me the water - Niemand kann mir das Wasser reichen",
                    "not the yellow of the egg - Nicht das Gelbe vom Ei",
                    "everything in green area - Alles im grünen Bereich",
                    "I die for Blackforrestcherrycake - Ich sterbe für Schwarzwälderkirschtorte",
                    "it walks me icecold the back down - Es läuft mir Eiskalt den Rücken runter",
                    "I´m foxdevilswild - Ich bin Fuchsteufelswild",
                    "How horny is that then !? - Wie Geil ist das denn!?",
                    "that goes away like Schmitz Cat - Das geht ab wie Schmitz Katze",
                    "nothing for ungood - Nichts für ungut",
                    "that makes me nobody so quickly after - Das macht mir keiner so leicht nach",
                    "that I don't laugh! - Das ich nicht lache!",
                    "I laugh me broken - Ich lach mich kaputt",
                    "I shame me in ground and floor - Ich schäm mich in Grund und Boden",
                    "I think my pig pipes - Ich glaub mein Schwein pfeift",
                    "that makes me nobody so easy after - Das macht mir keiner so leicht nach",
                    "this is so arm... - Das ist so arm...",
                    "Sponge over! - Schwamm drüber!",
                    "you come in devils kitchen - Du kommst in Teufelsküche",
                    "you foambeater, you! - Du Schaumschläger, Du!",
                    "that's a nice train from you - Das ist ein netter Zug von Dir",
                    "rip you together! - Reiss dich zusammen!",
                    "I think I break together - Ich glaub ich brech zusammen",
                    "the motive holies the middle - Das Motiv heiligt die Mittel",
                    "now we have the salad - Jetzt haben wir den Salat",
                    "there are laughing yes the chickens - Dach lachen ja die Hühner",
                    "that's not my beer - Das ist nicht mein Bier",
                    "that's one-wall-free - Das ist einwandfrei",
                    "I make me out of the dust - Ich mach mich aus dem Staub",
                    "you have a jump in the dish - Du hast einen Sprung in der Schuessel",
                    "you can me one time - Du kannst mich mal",
                    "us runs the water in the mouth together - uns laeuft das Wasser im Mund zusammen",
                    "to go someone on the glue - jemandem auf den Leim gehen",
                    "take yourself in eight - nimm dich in Acht",
                    "now we sit quite beautiful in the ink - jetzt sitzten wir ganz schoen in der Tinte",
                    "pain let after - Schmerz lass nach",
                    "me nothing, you nothing - mir nichts, dir nichts",
                    "hold the air on - halt die Luft an",
                    "it's me sausage - es ist mir Wurst",
                    "now is the oven out - jetzt ist der Ofen aus",
                    "shame you what - schäm' Dich was",
                    "equal goes it loose - gleich geht's los(celeb quote: Heinrich Lübke)",
                    "come clear! - Komm klar!",
                    "short and pregnant - Kurz und prägnant",
                    "that's me equal - Das ist mir egal",
                    "i wish you what - Ich wünsch Dir was",
                    "i press you the thumbs - Ich drück Dir die Daumen",
                    "hold the ears stiff - Halt die Ohren steif",
                    "you are heavy on wire - Du bist schwer auf Draht",
                    "I laugh me dead - Ich lach mich tot",
                    "I come me appled for - Ich komm mir verarscht vor",
                    "this can only a fun be - Das kann nur ein Spaß sein",
                    "I have now really the nose full - Ich hab jetzt wirklich die Nase voll",
                    "me reaches it - Mir reicht es",
                    "I have the muzzle full - Ich hab die Schnautze voll",
                    "I must overgive me - Ich muss mich übergeben",
                    "now hang I in the air - Jetzt häng ich in der Luft",
                    "where round goes it? - Worum geht es?",
                    "you luck mushroom - Du Glückspilz",
                    "I joy me already thereon - Ich freu mich schon drauf",
                    "don't you think this reaches now - Glaubst Du nicht es reicht jetzt?",
                    "I become the crisis - Ich bekomm die Krise",
                    "this is hammer hard - Das ist Hammerhart",
                    "dead said life longer - Tot gesagte leben länger",
                    "I have hunger - Ich habe hunger",
                    "now it's celebration evening - Jetzt ist es Feierabend",
                    "I must the bread-rolls earn - Ich muss die Brötchen verdienen",
                    "this here cannot be your earnest - Das hier kann nicht Dein Ernst sein",
                    "you must more train - Du musst mehr trainieren",
                    "chamber, chamber! - Gemach, gemach!",
                    "I stand on the tube - Ich steh aufm Schlauch",
                    "everything for the cat - Alles für die Katz",
                    "it knocks me out the socks - Es haut mich aus den Socken",
                    "me falls a stone from heart - Mir fällt ein Stein vom Herzen",
                    "me goes a light up - Mir geht ein Licht auf",
                    "you are going me on the alarm-clock - Du gehst mir aufn Wecker",
                    "now can come what want - Jetzt kann kommen was will",
                    "you can say you to me - Sie können Du zu mir sagen",
                    "don't go me on the ghost - Geh mir nicht auf den Geist",
                    "I can not more - Ich kann nicht mehr",
                    "I think it's hacking - Ich glaub es hackt",
                    "fun by side - Spaß bei Seite",
                    "is me boner - Ist mir Latte",
                    "now beats it but thirteen - Jetzt schlägt's aber dreizehn",
                    "this fits on no cowskin - Das passt auf keine Kuhhaut",
                    "you can take poison on it - Da kannst Du Gift drauf nehmen",
                    "you helped me no meter further - Du hast mir keinen Meter weitergeholfen",
                    "there you look stupid out of the laundry - Da guckst Du dumm aus der Wäsche",
                    "what's this for a juiceshop here? - Was ist das hier für ein Saftladen?",
                    "here is dead trousers - Hier ist tote Hose",
                    "again what learned - Wieder was gelernt",
                    "let the cat ouf of the bag - Lass die Katze ausm Sack",
                    "there goes the dog in the pan crazy - Da wird der Hund in der Pfanne verrückt",
                    "I clap you away! - Ich klatsch Dich weg!",
                    "scratch the turn - Kratz die Kurve",
                    "to dance around on someones nose - Jemandem auf der Nase herumtanzen",
                    "I think we are now in the devilsround - Ich glaube wir sind jetzt in einem Teufelskreis",
                    "for me goes that clear - Für mich geht das klar",
                    "double needled holds better - Doppelt genäht hält besser",
                    "play you yes not up - Spiel Dich ja nicht auf",
                    "don't tell me the blue from the heaven - Erzähl mir nicht das Blaue vom Himmel",
                    "draw not the devil on the wall - Mal nicht den Teufel an die Wand",
                    "Put a tooth to - Leg ein Zahn zu",
                    "life is no sugarlicking - Leben ist kein Zuckerschlecken",
                    "close aside is also over - Knapp daneben ist auch vorbei",
                    "he made us a line trough the bill - Er machte uns einen Strich durch die Rechnung",
                    "I know how the bunny is running - Ich weiß wie der Hase läuft",
                    "I throw me over the houses - Ich schmeiß mich über die Häuser",
                    "there are you flat what? - Da bist Du platt was?",
                    "that find I also - Das find ich auch",
                    "until equal - Bis gleich!",
                    "he made himself, me nothing, you nothing out of the dust - Er machte sich mir nichts, dir nichts aus dem Staub",
                    "silence in the box - Ruhe im Karton",
                    "that is jacket as trousers - Das ist Jacke wie Hose",
                    "that is me so what of sausage - Das ist mir sowas von Wurscht",
                    "how you me so I you - Wie Du mir, so ich Dir",
                    "leave the church in the village - Lass die Kirche im Dorf",
                    "how late is it on your watch? - Wie spät ist es auf Deiner Uhr?",
                    "who digs other one a hole, will fall himself in - Wer andern eine Grube gräbt, fällt selbst hinein",
                    "who fries other ones a sausage, has a sausage-frying-device - Wer andern eine Bratwurst brät, der hat ein Bratwurst-Bratgerät",
                    "I come good clear with my before seated - Mit meinem Vorgesetzten komm ich gut klar",
                    "I'm overseating all wordwordly - Ich übersetze alles wortwörtlich",
                    "now me walk the ideas out - Jetzt gehen mir die Ideen aus",
                    "you are such a pipe - Du bist so eine Pfeife",
                    "there is the crap steaming - Da ist die Kacke am Dampfen",
                    "the game walked out undecisioned - Das Spiel ging unentschieden aus",
                    "I think me louses the monkey - Ich glaub mich laust der Affe",
                    "there roll me the toenails high - Da rollen sich mir die Zehennägel hoch",
                    "you are a do-not-good - Du bist ein Tunichtgut",
                    "there I could go to the ceiling! - Da könnt ich an die Decke gehen!",
                    "you can slight my back down - Du kannst mir den Buckel runterrutschen",
                    "everytime slow, an old lady is no D-train - Immer langsam, eine alte Dame ist kein D-Zug",
                    "everything hangs together - Alles hängt zusammen",
                    "go there where the pepper grows - Geh dahin, wo der Pfeffer wächst",
                    "it's just a catjump from here - Das ist nur ein Katzensprung von hier",
                    "tell me the ground! - Sag mir den Grund!",
                    "my great before-picture - Mein großes Vorbild",
                    "only over my corpse! - Nur über meine Leiche!",
                    "how you me, so I you - Wie Du mir, so ich Dir!",
                    "lid to, monkey dead! - Deckel zu, Affe tot!",
                    "go before the dogs - Geh vor die Hunde",
                    "let the church in the village - Lass die Kirche im Dorf",
                    "Greet God - Grüß Gott",
                    "my pictureumbrella walks not - Mein Bildschirm geht nicht",
                    "I saw it in the farlooking. - Ich habs im Fernsehen gesehen.",
                    "this gives it yes not! - Das gibt's ja nicht!",
                    "say once, goes it you still or what? - Sag mal, gehts Dir noch oder was?",
                    "I can.t see the forest for louder trees - Ich kann den Wald vor lauter Bäumen nicht sehen",
                    "not equally fall with the door in the house - Nicht gleich mit der Tür ins Haus fallen",
                    "what a dog weather - Was für ein Hundewetter",
                    "you can slide me down the hump! - Du kannst mir den Buckel runter rutschen!",
                    "Skin off! - Haut ab!",
                    "now it goes loose - Jetzt gehts los",
                    "on every case - auf jeden Fall",
                    "I think I'm turning the wheel - Ich glaub, ich dreh am Rad",
                    "to have one on the wafer - einen an der Waffel haben",
                    "go to the page - geh zur Seite",
                    "he has it fistplump behind the ears - Er hat es Faustdick hinter den Ohren",
                    "I bring my sheep into the dry - Ich bringe meine Schäfchen ins Trockene",
                    "to step in the fatcup - ins Fettnäpfchen treten",
                    "out clear sky - Aus heiterem Himmel",
                    "come me not so! - Komm mir nicht so!",
                    "letting be five straight - Fünfe gerade sein lassen",
                    "who believes it, will be blessedly - Wer's glaubt wird selig",
                    "hold the ball flat - Halt den Ball flach",
                    "it burns me under the nails - Es brennt mir unter den Nägeln",
                    "too many cooks, ruin the mash - Zu viele Köche verderben den Brei",
                    "there I could puke - Da könnt ich kotzen",
                    "easy there along said - Einfach so daher gesagt",
                    "the jumping point is - Der springende Punkt ist",
                    "to speak in the highest sounds of somebody - In den höchsten Tönen von jemanden sprechen",
                    "you can you to the devil scissors - Du kannst Dich zum Teufel scheren",
                    "this is me so what from shit equal - Das ist mir sowas von scheiß egal",
                    "you want to sell me well for stupid - Du willst mich wohl für dumm verkaufen",
                    "I get my go stop over meadows - Ich bekomme mein Gehalt überwiesen",
                    "there lies the dog buried - Da liegt der Hund begraben",
                    "not bad Mr. Woodpecker - Nicht schlecht Herr Specht",
                    "this guy is washed with all waters - Der Kerl ist mit allen Wassern gewaschen",
                    "now I pull other pages up - Jetzt zieh ich andere Seiten auf",
                    "you beat yes completely new notes on - Du schlägst ja ganz neue Töne an",
                    "so becomes a shoe out of it - So wird ein Schuh draus",
                    "that is a strong piece - Das ist ein starkes Stück",
                    "oh you green nine - Ach du grüne Neune",
                    "very first cream - Aller erste Sahne",
                    "lie on the lazy skin - Auf der faulen Haut liegen",
                    "feel somebody on the tooth - Jemandem auf den Zahn fühlen",
                    "bind somebody something on the nose - Jemandem etwas auf die Nase binden",
                    "out the mouse - Aus die Maus",
                    "the eye eats with - Das Auge isst mit",
                    "that comes me not in the bag - Das kommt mir nicht in die Tüte",
                    "hold the edge - Halt den Rand",
                    "pull the ass card - Die Arschkarte ziehen",
                    "push a silent bowl - eine ruhige Kugel schieben",
                    "Peace, Joy, Pancake - Friede, Freude, Eierkuchen",
                    "come in the Corridors - In die Gänge kommen",
                    "ask someone a hole in the stomach - Jemandem ein Loch in den Bauch fragen",
                    "you bring me on the palm - Du bringst mich auf die Palme",
                    "see to that you win land - Sieh zu, dass du Land gewinnst",
                    "makes nothing - Macht nichts",
                    "not from bad parents - Nicht von schlechten Eltern",
                    "that goes you nothing on - Das geht Dich nichts an",
                    "bullshit with sauce - Quatsch mit Soße",
                    "grap you a heart - Fass dir ein Herz",
                    "make a fly - Mach ne Fliege",
                    "there is something in the bush - Da ist was im Busch",
                    "to put honey around someone's mouth - Jemandem Honig ums Maul schmieren",
                    "take place please - Nehmen Sie Platz bitte",
                    "it borders on a wonder - Es grenzt an ein Wunder",
                    "stand you not so on - Stell Dich nicht so an",
                    "understand you - Untersteh Dich",
                    "always the nose after - Immer der Nase nach",
                    "today we make one on top - Heute machen wir einen drauf",
                    "thank you for the afterquestion - Danke der Nachfrage",
                    "she has to buffalo for school - Sie muss für die Schule büffeln",
                    "not over after thought - Nicht drüber nachgedacht",
                    "you have this at your hairs overpulled - Du hast das an deinen Haaren herbeigezogen",
                    "all in butter - Alles in Butter",
                    "everything is in the plumb line - Alles ist im Lot",
                    "older Swede - Alter Schwede",
                    "down through the middle - Ab durch die Mitte",
                    "oh you lovely sky - Ach du lieber Himmel",
                    "I'm at the end of my latin - Ich bin mit meinem Latein am Ende",
                    "don't play the offended liversausage - Spiel nicht die beleidigte Leberwurst",
                    "don.t try to bind me a bear on - Versuch mir nicht einen Bären aufzubinden",
                    "he has come on the dog - Er ist auf den Hund gekommen",
                    "it was pig smooth - Es war sauglatt",
                    "you can climb my hump up - Du kannst mir den Buckel hinaufsteigen",
                    "he shall me not so come - Er soll mir nicht so kommen",
                    "always the equal piss - Immer die gleiche Seiche",
                    "me can nobody what - Mir kann niemand was",
                    "what for an onefall - Was für ein Einfall",
                    "I show you, where the Beardly gets the cider from - Ich zeig Dir, wo der Bartli den Most holt",
                    "that walks yes not at all - Das geht ja gar nicht",
                    "on and for itself - An und für sich",
                    "in ground taken - Im Grunde genommen",
                    "This is oil on my soul - Das ist Balsam für meine Seele",
                    "on devil come out - Auf Teufel komm raus",
                    "so looks it out - So schaut's aus",
                    "what also ever - Was auch immer",
                    "understand you - untersteh Dich",
                    "I have afterpush for you - Ich hab Nachschub für Euch",
                    "the egglaying woolmilkpig - Die eierlegende Wollmilchsau",
                    "can I become some aftertable - Kann ich etwas Nachtisch bekommen",
                    "that fits in the back and in the front not - Das passt vorn und hinten nicht",
                    "I am twisting at the wheel - Ich drehe am Rad",
                    "there is sand in the transmission - Da ist Sand im Getriebe",
                    "what shalls? - Was solls?",
                    "how goes it you? - Wie geht's Dir?",
                    "thanks, it walks so - Danke, es geht so",
                    "Beat in! - Hau rein!",
                    "now is the oven is out - jetzt ist der Ofen ist aus",
                    "I fall around - ich fall um",
                    "this catches yes good on - Das fängt ja gut an",
                    "I make little wood out of you - ich mach Kleinholz aus Dir",
                    "I think I hear not right - ich glaub ich hör nicht recht",
                    "I will the child already swing - ich werde das Kind schon schaukeln",
                    "it interest me not the bean - es interessiert mich nicht die Bohne",
                    "the life is not a wish-concert - Das Leben ist kein Wunschkonzert",
                    "there goes the dog in the pan crazy - da wird der Hund in der Pfanne verückt",
                    "I add a little bit - ich geb klein bei",
                    "I make me on the sock - ich mach mich auf die Socken",
                    "go me not on the bag - geh mir nicht auf den Sack",
                    "there fry me someone a stork - da brat mir einer nen Storch",
                    "that comes overhead not in question - das kommt überhaupt nicht in Frage",
                    "don't bring me on the palm - bring mich nicht auf die Palme",
                    "I hold that not out - Ich halte das nicht aus",
                    "to empty in one train - in einem Zug leeren",
                    "I am throughlooking you - Ich durchschaue dich",
                    "I make you fix and ready - Ich mach dich fix und fertig",
                    "I must make a little business - Ich muss ein kleines Geschäft machen",
                    "she goes professionally online - Sie geht beruflich auf den Strich",
                    "pull line! - Zieh Leine!",
                    "you have a screw loose - du hast eine Schraube locker",
                    "it pulls like pike soup - es zieht wie Hechtsuppe",
                    "on never-again-see - auf Nimmerwiedersehen",
                    "a blind chicken finds too once a grain - in blindes Huhn findet auch einmal ein Korn",
                    "it is yet not all days evening - es ist noch nicht aller Tage Abend",
                    "to look over the own dish border - über den eigenen Tellerrand schauen",
                    "who not hear will must feel - wer nicht hören will muss fühlen",
                    "to ondigger somone - jemanden anbaggern",
                    "that beats the barrel the bottom out - das schlägt dem Faß den Boden aus",
                    "to have mush wood before the cottage - viel Holz vor der Hütte haben",
                    "I give to that - Ich gebe zu dass",
                    "to see the radishes from down - Die Radieschen von unten sehen",
                    "there lies the rabbit in the pepper - da liegt der Hase im Pfeffer",
                    "I hit me on the ear - ich hau mich aufs ohr",
                    "I spin through - ich dreh durch",
                    "you are walking me on the bag - Du gehst mir auf den Sack",
                    "he made the invoice without the innkeeper. - Er hat die Rechnung ohne den Wirt gemacht.",
                    "it's sausage - es ist wurst",
                    "it hits full inside - das haut voll rein",
                    "that comes overhead not in the bag - das kommt überhaupt nicht in Frage",
                    "you have a wheel off - Du hast ein Rad ab",
                    "Look me not so strange on - schau mich nicht so komisch an",
                    "iIt still goes again - es geht schon wieder",
                    "that was all for the ass - das war alles fürn ar***",
                    "do you have a bird? - hast du nen Vogel?",
                    "enjoy life in full trains - das Leben in vollen Zügen genießen",
                    "I show you on - ich zeig Dich an",
                    "to push a quiet number - eine ruhige Nummer schieben",
                    "don't guide me behind the light - führ mich nicht hinters Licht",
                    "my friend and copper plate engraver - mein Freund und Kupferstecher",
                    "you have not all boners on the fence - Du hast nicht mehr alle Latten am Zaun",
                    "he is over the mountain - Er ist übern Bergno",
                    "Jack Steam in all alleys - Hans Dampf in allen Gassen",
                    "if you believe you can beat me over the ear - wenn sie glauben, dass sie mich übers Ohr hauen können",
                    "cost it what it will - koste es was es wolle",
                    "my car gave up the ghost - mein Auto hat den Geist aufgegeben",
                    "on bend and break - auf biegen und brechen",
                    "all to his time - alles zu seiner zeit",
                    "make me not on - mach mich nicht an",
                    "you walk me on the eggs - du gehst mir auf die eier",
                    "to hell still meal - zur hölle noch mal",
                    "picture you not so much on - bild dir nicht so viel ein",
                    "there lie you false - da liegst du falsch",
                    "lowminder - schwachsinniger",
                    "such a low mind - so ein schwachsinn",
                    "hear up to thinking - hör auf zu denken",
                    "I think me kicks a horse! - Ich glaub' mich tritt ein Pferd!",
                    "who has the has - Wer hat der hat",
                    "A gifted horse looks one not in the mouth - Einem geschenkten Gaul schaut man nicht ins Maul",
                    "you can me multiplied crosswise - Du kannst mich mal kreuzweise!",
                    "this might go heavily in the throusers! - das kann schwer in die Hose gehen!",
                    "I help you on the jumps - ich helf dir auf die Sprünge",
                    "don't buy the pussy in the bag - kauf nicht die Katze im Sack",
                    "I have something to kill - Ich habe noch etwas zu erledigen",
                    "a sharp device - ein scharfes Gerät",
                    "he has nothing to search here - der hat hier nichts zu suchen.",
                    "please bring hunger with - Bitte Hunger mitbringen",
                    "you clever shitter - Du Klugscheisser",
                    "that goes me on the pointer - Das geht mir auf den Zeiger",
                    "you fall out of the roll - du fällst aus der Rolle",
                    "something fits today not - irgendwas passt heute nicht",
                    "no watch thing - Keine Ursache",
                    "that gives murder and deadpunch - Das gibt Mord und Totschlag",
                    "morning hour has gold in the mouth - Morgenstund hat Gold im Mund",
                    "I am totally glowing - ich bin total begeistert",
                    "one back the bandage spilling - Einen hinter die Binde giessen",
                    "this makes me foxy - das macht mich fuchsig",
                    "please hold the gob - Halt bitte die Fresse",
                    "What falls you actually on? - Was fällt dir eigentlich ein?",
                    "you grin yes how a honeycakehorse. - Du grinst ja wie ein Honigkuchenpferd.",
                    "Girls are good to birds - Mädchen sind gut zu vögeln",
                    "I am the great before sitter - ich bin der grosse Vorsitzender",
                    "A times is no times. - Einmal ist keinmal.",
                    "That makes the bock too not fat - das macht den bock auch nicht fett",
                    "I have the nose painted full - Ich habe die Nase gestrichen voll",
                    "I white it not! - Ich weiss es nicht!",
                    "there must we through - da müssen wir durch",
                    "your dog is not online - ihr Hund ist nicht angeleint",
                    "You must also always everywhere adding your mustard, what? - Du musst auch immer überall Deinen Senf hinzufügen, was?",
                    "it pulls like fishsoup - es zieht wie hechtsuppe",
                    "I have the nose painted full - Ich hab' die Nase gestrichen voll",
                    "Yes, no is clear - Ja, nee is klar",
                    "this is not the screamer - das ist nicht der Brüller",
                    "What to the devil is loose with you? - Was zum Teufel ist los mit dir?",
                    "Get you one again - Krieg Dich wieder ein",
                    "Do you want to take me on your arm? - Willst du mich auf den Arm nehmen?",
                    "I stick you one - Ich kleb dir eine!",
                    "Always breathe loose through the trousers - Immer locker durch die Hose atmen",
                    "bekannt sein wie ein bunter Hund - well-known like a colorful dog",
                    "I barrel it not - Ich fass es nicht",
                    "to cash a running-in - einen Einlauf kassieren",
                    "That shoe I don't pull me on - Den Schuh zieh' ich mir nicht an",
                    "I don't trust that roastbeef - Ich trau' dem Braten nicht",
                    "I voice you too - I stimme Dir zu",
                    "that doesn't bring me anything - das bringt mir nichts",
                    "shit the wall on - scheiss die Wand an",
                    "are you still to rescue? - Bist du noch zu retten?",
                    "This ist not to catch! - Das ist nicht zu fassen!",
                    "Get you again one! - Krieg dich wieder ein!hehehe",
                    "Hit off! - Hau ab!",
                    "you can me crosswise - du kannst mich kreuzweise",
                    "Oh you lovely nine! - Ach du liebe Neune!",
                    "Give eight! - Gib Acht!",
                    "You have a screw easy! - Du hast eine Schraube locker!",
                    "The devil shits the biggest hill - Der Teufel scheißt den dicksten Haufen",
                    "holy Indian-honor-word - heiliges Indianer Ehrenwort",
                    "greet god - Grüß Gott",
                    "from me out - von mir aus",
                    "I look not back, I look in front - Ich schau nicht zurück, ich schau nach vorn (celeb quote: Lothar Matthäus)",
                    "you drive me up the wall - du fährst mich die Wand herauf",
                    "you have it fistthick behind the ears - du hast es Faustdick hinter den Ohren",
                    "you have the whiteness with spoons eaten - du hast die Weisheit mit Löffeln gefressen",
                    "that shoots the bird down - das schießt den Vogel ab",
                    "it was all for the cat - es war alles für die Katz",
                    "againseeing makes happyness - Wiedersehen macht Freude",
                    "swinging the eggs - Die Eier schaukeln",
                    "To search yourself the wolf - Sich den Wolf absuchen",
                    "Where does the shoe push? - Wo drückt der Schuh?",
                    "to pepper something into the corner - Etwas in die Ecke pferrern",
                    "I do only so - Ich tu nur so",
                    "dull is trump - Stumpf is Trumpf.",
                    "to come out of the curd - aus dem quark kommen",
                    "there your ass is going on ground ice - da geht dir der arsch auf grundeis",
                    "it empires now - es reicht jetzt",
                    "to have much wood before the cottage - viel Holz vor der Hütte habenmush ist falsch geschrieben - much",
                    "that goes but not - Das geht aber nicht!",
                    "I think i spin the wheel - Ich glaub ich dreh am Rad",
                    "You know how the rabbit runs - Du weißt, wie der Hase läuft",
                    "I get a bird! - Ich krieg nen Vogel!",
                    "Thats not close full-permanently - Das ist nicht ganz vollständig",
                    "Im not total right in the head - ich bin nicht ganz richtig im Kopf",
                    "You have no idea of tooting and blowing - Du hast von Tuten und Blasen keine Ahnung",
                    "all braggards without gun - alle Angaben ohne Gewähr",
                    "There crows no rooster after - Da kräht kein Hahn danach",
                    "That delivers me nothing! - Das bringt mir granichts!",
                    "we can go i am so far - wir können gehen ich bin so weit",
                    "mine humble opinion after - meiner bescheidenen Meinung nach",
                    "I´ll make you all ready - Ich mach Euch alle fertig!",
                    "you have a jump in the dish - du hast nen Sprung in der Schüssel",
                    "in the shortness lies the spice - in der Küze liegt die Würze",
                    "to come on the dog - auf den Hund kommen",
                    "I don´t put me this shoe on - Den Schuh ziehe ich mir nicht an",
                    "i have evil one in the tea - ich hab böse einen im tee",
                    "He is to table! - Er ist zu Tisch!",
                    "i have it not necessary - ich habe es nicht nötig",
                    "That is yes offdriven! - Das ist ja abgefahren!",
                    "Attention is the mother of the chinaware box! - Vorsicht ist die Mutter der Porzellankiste !",
                    "It fits how the fist on the eye - Es passt wie die Faust aufs Auge",
                    "pig had! - schwein gehabt!",
                    "That is whole big cinema - Das ist ganz grosses Kino",
                    "I sit me in movement - Ich setz mich in Bewegung",
                    "there hits it me the bird out - da haut es mir den Vogel raus",
                    "Come good home - Komm gut nach Hause",
                    "Now is end with funny - Jetzt ist Schluss mit lustig",
                    "This is the Hopsingpoint - Das ist der springende Punkt",
                    "You are a real funbird - Du bist ein echter Spaßvogel",
                    "to let somebody forhunger at the long arm - Jemanden am langen Arm verhungern lassen",
                    "I have such a neck! - Ich hab so einen Hals!",
                    "That is hearing itself good on - Das hört sich gut an",
                    "heaven thunderweather! my farseeing picture-umbrella is in the bucket - Himmeldonnerwetter! Mein Fernsehbildschirm ist im Eimer.",
                    "Not so fast, friendy! - Nicht so schnell, Freundchen!",
                    "Dare you yes not! - Trau dich ja nicht!",
                    "Can you tell me where here the bear is tap-dancing? - Kannst Du mir sagen, wo hier der Bär steppt?",
                    "my watercock drops - Mein Wasserhahn tropft",
                    "But something like this from - Aber sowas von!",
                    "i get a hair dryer - ich krieg einen fön",
                    "that went into the eye - das ist ins auge gegangen",
                    "You lazy sock! - Du faule Socke!",
                    "Ask me once! - Frag mich mal!",
                    "I make you flat! - Ich mach dich platt!",
                    "Look shut that you win country - Sieh zu daß Du Land gewinnst",
                    "heavy on wire - schwer auf Draht",
                    "what be must must be - was sein muss muss sein",
                    "structured selction wrong driving - strukturiertes Auswahlverfahren",
                    "It hangs me to the throat out - Es hängt mir zum Hals raus",
                    "Then you look dumb out of the laundry - Dann kuckst Du dumm aus der Wäsche",
                    "it goes under and over - es geht drunter und drüber",
                    "Who can the can. - Wer kann, der kann.",
                    "it´s shift in the shaft - Es ist Schicht im Schacht",
                    "this is yes a chubby dog! - Das ist ja ein dicker Hund!",
                    "Here is but fat air - Hier ist aber dicke Luft",
                    "I am totally awaykicked - Ich bin völlig weggetreten",
                    "it reaches sportfriend - Es reicht, Sportsfreund !",
                    "to have one in the waffel - einen in der Waffel haben",
                    "it is to milk mice - es ist zum Mäuse melken",
                    "I will have one eye on it - ich werde ein Auge darauf haben",
                    "that is yes everything nice and good - das ist ja alles schön und gut",
                    "this pulls you the shoes out - das zieht dir die Schuhe aus",
                    "I make you fix and ready - Ich mach dich fix und fertig",
                    "She walks professionally online - Sie geht beruflich auf den Strich",
                    "alien speaking course - Fremdsprachenkurs",
                    "he is good arriving at the girls - er kommt bei den Mädchen gut an",
                    "That comes overhead not in question! - Das kommt überhaupt nicht in Frage!",
                    "jokecookie - Scherzkeks",
                    "go me not on the bag - geh mir nicht auf den Sack",
                    "on neveragainsee - auf nimmer Wiedersehen",
                    "The oven is out - Der Ofen ist aus",
                    "Thank you for the fruitful discussion - Danke, für die fruchtbare Diskussion",
                    "I think you walk too good - Ich glaub dir gehts zu gut",
                    "Without anybody too near kick to want - Ohne jemandem zu nahe treten zu wollen",
                    "Now make nails with heads - Jetzt mach mal Nägel mit Köpfen",
                    "Have you them still all? - Hast du sie noch alle?",
                    "under all cannon - unter aller Kanone",
                    "The inside pig dog - Der innere Schweinehund",
                    "that stands like a one - das steht wie eine eins",
                    "I hit me away - Ich hau mich weg",
                    "i have the turn out - Ich hab den Dreh raus",
                    "The bride has a nice chassis! - Die Braut hat ein schönes Fahrgestell",
                    "that goes you a wet brushing on - Das geht Dich einen feuchten Kehricht an",
                    "you smart shitter - du Klugscheisser",
                    "that is but shit - das ist aber Scheiße",
                    "why so ever - warum auch immer"};

    private static final Random RANDOM = new Random();

    public String random() {
        return FACTS[RANDOM.nextInt(FACTS.length)];
    }
}
