/**
 * Copyright (c) 2009 Cliffano Subagio
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package hudson.plugins.denglish;

import java.util.Random;

/**
 * {@link FactGenerator} provides denglish facts.
 * @author cliffano
 */
public class FactGenerator {

    /**
     * The configured denglish facts, from <a href="http://www.codesqueeze.com/the-ultimate-top-25-chuck-norris-the-programmer-jokes/"
     * >http://www.codesqueeze.com/the-ultimate-top-25-chuck-norris-the-
     * programmer-jokes/</a>.
     */
    private static final String[] FACTS = {
                    "I understand just train-station",
                    "sorry, my englisch is under all pig",
                    "I think I spider",
                    "the devil will i do",
                    "my lovely mister singing club",
                    "come on...jump over your shadow",
                    "you walk me animally on the cookie",
                    "there my hairs stand up to the mountain",
                    "tell me nothing from the horse",
                    "don´t ask after sunshine",
                    "it´s not good cherry-eating with you",
                    "now it goes around the sausage",
                    "there are you on the woodway",
                    "holla the woodfairy",
                    "I hold it in head not out",
                    "now butter by the fishes",
                    "I see black for you",
                    "your are such a fear-rabbit",
                    "known home luck alone",
                    "are you save?",
                    "give not so on",
                    "heaven, ass and thread!",
                    "Human Meier",
                    "you have not more all cups in the board",
                    "she had a circleruntogetherbreak",
                    "I know me here out",
                    "I fall from all clouds",
                    "no one can reach me the water",
                    "not the yellow of the egg",
                    "everything in green area",
                    "I die for Blackforrestcherrycake",
                    "it walks me icecold the back down",
                    "I´m foxdevilswild",
                    "How horny is that then !?",
                    "that goes away like Schmitz Cat",
                    "nothing for ungood",
                    "that makes me nobody so quickly after",
                    "that I don't laugh!",
                    "I laugh me broken",
                    "I shame me in ground and floor",
                    "I think my pig pipes",
                    "that makes me nobody so easy after",
                    "this is so arm...",
                    "Sponge over!",
                    "you come in devils kitchen",
                    "you foambeater, you!",
                    "that's a nice train from you",
                    "rip you together!",
                    "I think I break together",
                    "the motive holies the middle",
                    "now we have the salad",
                    "there are laughing yes the chickens",
                    "that's not my beer",
                    "that's one-wall-free",
                    "I make me out of the dust",
                    "you have a jump in the dish",
                    "you can me one time",
                    "us runs the water in the mouth together",
                    "to go someone on the glue",
                    "take yourself in eight",
                    "now we sit quite beautiful in the ink",
                    "pain let after",
                    "me nothing, you nothing",
                    "hold the air on",
                    "it's me sausage",
                    "now is the oven out",
                    "shame you what",
                    "equal goes it loose",
                    "come clear!",
                    "short and pregnant",
                    "that's me equal",
                    "i wish you what",
                    "i press you the thumbs",
                    "hold the ears stiff",
                    "you are heavy on wire",
                    "I laugh me dead",
                    "I come me appled for",
                    "this can only a fun be",
                    "I have now really the nose full",
                    "me reaches it",
                    "I have the muzzle full",
                    "I must overgive me",
                    "now hang I in the air",
                    "where round goes it?",
                    "you luck mushroom",
                    "I joy me already thereon",
                    "don't you think this reaches now",
                    "I become the crisis",
                    "this is hammer hard",
                    "dead said life longer",
                    "I have hunger",
                    "now it's celebration evening",
                    "I must the bread-rolls earn",
                    "this here cannot be your earnest",
                    "you must more train",
                    "chamber, chamber!",
                    "I stand on the tube",
                    "everything for the cat",
                    "it knocks me out the socks",
                    "me falls a stone from heart",
                    "me goes a light up",
                    "you are going me on the alarm-clock",
                    "now can come what want",
                    "you can say you to me",
                    "don't go me on the ghost",
                    "I can not more",
                    "I think it's hacking",
                    "fun by side",
                    "is me boner",
                    "now beats it but thirteen",
                    "this fits on no cowskin",
                    "you can take poison on it",
                    "you helped me no meter further",
                    "there you look stupid out of the laundry",
                    "what's this for a juiceshop here?",
                    "here is dead trousers",
                    "again what learned",
                    "let the cat ouf of the bag",
                    "there goes the dog in the pan crazy",
                    "I clap you away!",
                    "scratch the turn",
                    "to dance around on someones nose",
                    "I think we are now in the devilsround",
                    "for me goes that clear",
                    "double needled holds better",
                    "play you yes not up",
                    "don't tell me the blue from the heaven",
                    "draw not the devil on the wall",
                    "Put a tooth to",
                    "life is no sugarlicking",
                    "close aside is also over",
                    "he made us a line trough the bill",
                    "I know how the bunny is running",
                    "I throw me over the houses",
                    "there are you flat what?",
                    "that find I also",
                    "until equal",
                    "he made himself, me nothing, you nothing out of the dust",
                    "silence in the box",
                    "that is jacket as trousers",
                    "that is me so what of sausage",
                    "how you me so I you",
                    "leave the church in the village",
                    "how late is it on your watch?",
                    "who digs other one a hole, will fall himself in",
                    "who fries other ones a sausage, has a sausage-frying-device",
                    "I come good clear with my before seated",
                    "I'm overseating all wordwordly",
                    "now me walk the ideas out",
                    "you are such a pipe",
                    "there is the crap steaming",
                    "the game walked out undecisioned",
                    "I think me louses the monkey",
                    "there roll me the toenails high",
                    "you are a do-not-good",
                    "there I could go to the ceiling!",
                    "you can slight my back down",
                    "everytime slow, an old lady is no D-train",
                    "everything hangs together",
                    "go there where the pepper grows",
                    "it's just a catjump from here",
                    "tell me the ground!",
                    "my great before-picture",
                    "only over my corpse!",
                    "how you me, so I you",
                    "lid to, monkey dead!",
                    "go before the dogs",
                    "let the church in the village",
                    "Greet God",
                    "my pictureumbrella walks not",
                    "I saw it in the farlooking.",
                    "this gives it yes not!",
                    "say once, goes it you still or what?",
                    "I can.t see the forest for louder trees",
                    "not equally fall with the door in the house",
                    "what a dog weather",
                    "you can slide me down the hump!",
                    "Skin off!",
                    "now it goes loose",
                    "on every case",
                    "I think I'm turning the wheel",
                    "to have one on the wafer",
                    "go to the page",
                    "he has it fistplump behind the ears",
                    "I bring my sheep into the dry",
                    "to step in the fatcup",
                    "out clear sky",
                    "come me not so!",
                    "letting be five straight",
                    "who believes it, will be blessedly",
                    "hold the ball flat",
                    "it burns me under the nails",
                    "too many cooks, ruin the mash",
                    "there I could puke",
                    "easy there along said",
                    "the jumping point is",
                    "to speak in the highest sounds of somebody",
                    "you can you to the devil scissors",
                    "this is me so what from shit equal",
                    "you want to sell me well for stupid",
                    "I get my go stop over meadows",
                    "there lies the dog buried",
                    "not bad Mr. Woodpecker",
                    "this guy is washed with all waters",
                    "now I pull other pages up",
                    "you beat yes completely new notes on",
                    "so becomes a shoe out of it",
                    "that is a strong piece",
                    "oh you green nine",
                    "very first cream",
                    "lie on the lazy skin",
                    "feel somebody on the tooth",
                    "bind somebody something on the nose",
                    "out the mouse",
                    "the eye eats with",
                    "that comes me not in the bag",
                    "hold the edge",
                    "pull the ass card",
                    "push a silent bowl",
                    "Peace, Joy, Pancake",
                    "come in the Corridors",
                    "ask someone a hole in the stomach",
                    "you bring me on the palm",
                    "see to that you win land",
                    "makes nothing",
                    "not from bad parents",
                    "that goes you nothing on",
                    "bullshit with sauce",
                    "grap you a heart",
                    "make a fly",
                    "there is something in the bush",
                    "to put honey around someone's mouth",
                    "take place please",
                    "it borders on a wonder",
                    "stand you not so on",
                    "understand you",
                    "always the nose after",
                    "today we make one on top",
                    "thank you for the afterquestion",
                    "she has to buffalo for school",
                    "not over after thought",
                    "you have this at your hairs overpulled",
                    "all in butter",
                    "everything is in the plumb line",
                    "older Swede",
                    "down through the middle",
                    "oh you lovely sky",
                    "I'm at the end of my latin",
                    "don't play the offended liversausage",
                    "don.t try to bind me a bear on",
                    "he has come on the dog",
                    "it was pig smooth",
                    "you can climb my hump up",
                    "he shall me not so come",
                    "always the equal piss",
                    "me can nobody what",
                    "what for an onefall",
                    "I show you, where the Beardly gets the cider from",
                    "that walks yes not at all",
                    "on and for itself",
                    "in ground taken",
                    "This is oil on my soul",
                    "on devil come out",
                    "so looks it out",
                    "what also ever",
                    "understand you",
                    "I have afterpush for you",
                    "the egglaying woolmilkpig",
                    "can I become some aftertable",
                    "that fits in the back and in the front not",
                    "I am twisting at the wheel",
                    "there is sand in the transmission",
                    "what shalls?",
                    "how goes it you?",
                    "thanks, it walks so",
                    "Beat in!",
                    "now is the oven is out",
                    "I fall around",
                    "this catches yes good on",
                    "I make little wood out of you",
                    "I think I hear not right",
                    "I will the child already swing",
                    "it interest me not the bean",
                    "the life is not a wish-concert",
                    "there goes the dog in the pan crazy",
                    "I add a little bit",
                    "I make me on the sock",
                    "go me not on the bag",
                    "there fry me someone a stork",
                    "that comes overhead not in question",
                    "don't bring me on the palm",
                    "I hold that not out",
                    "to empty in one train",
                    "I am throughlooking you",
                    "I make you fix and ready",
                    "I must make a little business",
                    "she goes professionally online",
                    "pull line!",
                    "you have a screw loose",
                    "it pulls like pike soup",
                    "on never-again-see",
                    "a blind chicken finds too once a grain",
                    "it is yet not all days evening",
                    "to look over the own dish border",
                    "who not hear will must feel",
                    "to ondigger somone",
                    "that beats the barrel the bottom out",
                    "to have mush wood before the cottage",
                    "I give to that",
                    "to see the radishes from down",
                    "there lies the rabbit in the pepper",
                    "I hit me on the ear",
                    "I spin through",
                    "you are walking me on the bag",
                    "he made the invoice without the innkeeper.",
                    "it's sausage",
                    "it hits full inside",
                    "that comes overhead not in the bag",
                    "you have a wheel off",
                    "Look me not so strange on",
                    "iIt still goes again",
                    "that was all for the ass",
                    "do you have a bird?",
                    "enjoy life in full trains",
                    "I show you on",
                    "to push a quiet number",
                    "don't guide me behind the light",
                    "my friend and copper plate engraver",
                    "you have not all boners on the fence",
                    "he is over the mountain",
                    "Jack Steam in all alleys",
                    "if you believe you can beat me over the ear",
                    "cost it what it will",
                    "my car gave up the ghost",
                    "on bend and break",
                    "all to his time",
                    "make me not on",
                    "you walk me on the eggs",
                    "to hell still meal",
                    "picture you not so much on",
                    "there lie you false",
                    "lowminder",
                    "such a low mind",
                    "hear up to thinking",
                    "I think me kicks a horse!",
                    "who has the has",
                    "A gifted horse looks one not in the mouth",
                    "you can me multiplied crosswise",
                    "this might go heavily in the throusers!",
                    "I help you on the jumps",
                    "don't buy the pussy in the bag",
                    "I have something to kill",
                    "a sharp device",
                    "he has nothing to search here",
                    "please bring hunger with",
                    "you clever shitter",
                    "that goes me on the pointer",
                    "you fall out of the roll",
                    "something fits today not",
                    "no watch thing",
                    "that gives murder and deadpunch",
                    "morning hour has gold in the mouth",
                    "I am totally glowing",
                    "one back the bandage spilling",
                    "this makes me foxy",
                    "please hold the gob",
                    "What falls you actually on?",
                    "you grin yes how a honeycakehorse.",
                    "Girls are good to birds",
                    "I am the great before sitter",
                    "A times is no times.",
                    "That makes the bock too not fat",
                    "I have the nose painted full",
                    "I white it not!",
                    "there must we through",
                    "your dog is not online",
                    "You must also always everywhere adding your mustard, what?",
                    "it pulls like fishsoup",
                    "I have the nose painted full",
                    "Yes, no is clear",
                    "this is not the screamer",
                    "What to the devil is loose with you?",
                    "Get you one again",
                    "Do you want to take me on your arm?",
                    "I stick you one",
                    "Always breathe loose through the trousers",
                    "bekannt sein wie ein bunter Hund",
                    "I barrel it not",
                    "to cash a running-in",
                    "That shoe I don't pull me on",
                    "I don't trust that roastbeef",
                    "I voice you too",
                    "that doesn't bring me anything",
                    "shit the wall on",
                    "are you still to rescue?",
                    "This ist not to catch!",
                    "Get you again one!",
                    "Hit off!",
                    "you can me crosswise",
                    "Oh you lovely nine!",
                    "Give eight!",
                    "You have a screw easy!",
                    "The devil shits the biggest hill",
                    "holy Indian-honor-word",
                    "greet god",
                    "from me out",
                    "I look not back, I look in front",
                    "you drive me up the wall",
                    "you have it fistthick behind the ears",
                    "you have the whiteness with spoons eaten",
                    "that shoots the bird down",
                    "it was all for the cat",
                    "againseeing makes happyness",
                    "swinging the eggs",
                    "To search yourself the wolf",
                    "Where does the shoe push?",
                    "to pepper something into the corner",
                    "I do only so",
                    "dull is trump",
                    "to come out of the curd",
                    "there your ass is going on ground ice",
                    "it empires now",
                    "to have much wood before the cottage",
                    "that goes but not",
                    "I think i spin the wheel",
                    "You know how the rabbit runs",
                    "I get a bird!",
                    "Thats not close full-permanently",
                    "Im not total right in the head",
                    "You have no idea of tooting and blowing",
                    "all braggards without gun",
                    "There crows no rooster after",
                    "That delivers me nothing!",
                    "we can go i am so far",
                    "mine humble opinion after",
                    "I´ll make you all ready",
                    "you have a jump in the dish",
                    "in the shortness lies the spice",
                    "to come on the dog",
                    "I don´t put me this shoe on",
                    "i have evil one in the tea",
                    "He is to table!",
                    "i have it not necessary",
                    "That is yes offdriven!",
                    "Attention is the mother of the chinaware box!",
                    "It fits how the fist on the eye",
                    "pig had!",
                    "That is whole big cinema",
                    "I sit me in movement",
                    "there hits it me the bird out",
                    "Come good home",
                    "Now is end with funny",
                    "This is the Hopsingpoint",
                    "You are a real funbird",
                    "to let somebody forhunger at the long arm",
                    "I have such a neck!",
                    "That is hearing itself good on",
                    "heaven thunderweather! my farseeing picture-umbrella is in the bucket",
                    "Not so fast, friendy!",
                    "Dare you yes not!",
                    "Can you tell me where here the bear is tap-dancing?",
                    "my watercock drops",
                    "But something like this from",
                    "i get a hair dryer",
                    "that went into the eye",
                    "You lazy sock!",
                    "Ask me once!",
                    "I make you flat!",
                    "Look shut that you win country",
                    "heavy on wire",
                    "what be must must be",
                    "structured selction wrong driving",
                    "It hangs me to the throat out",
                    "Then you look dumb out of the laundry",
                    "it goes under and over",
                    "Who can the can.",
                    "it´s shift in the shaft",
                    "this is yes a chubby dog!",
                    "Here is but fat air",
                    "I am totally awaykicked",
                    "it reaches sportfriend",
                    "to have one in the waffel",
                    "it is to milk mice",
                    "I will have one eye on it",
                    "that is yes everything nice and good",
                    "this pulls you the shoes out",
                    "I make you fix and ready",
                    "She walks professionally online",
                    "alien speaking course",
                    "he is good arriving at the girls",
                    "That comes overhead not in question!",
                    "jokecookie",
                    "go me not on the bag",
                    "on neveragainsee",
                    "The oven is out",
                    "Thank you for the fruitful discussion",
                    "I think you walk too good",
                    "Without anybody too near kick to want",
                    "Now make nails with heads",
                    "Have you them still all?",
                    "under all cannon",
                    "The inside pig dog",
                    "that stands like a one",
                    "I hit me away",
                    "i have the turn out",
                    "The bride has a nice chassis!",
                    "that goes you a wet brushing on",
                    "you smart shitter",
                    "that is but shit",
                    "why so ever"};

    /**
     * Random instance.
     */
    private static final Random RANDOM = new Random();

    /**
     * Retrieves a random fact.
     * @return a random fact
     */
    public String random() {
        return FACTS[RANDOM.nextInt(FACTS.length)];
    }
}
